---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Create ONTAP/ONTAP SnapMirror Update
  tasks:
  - name: Create ONTAP/ONTAP SnapMirror Update
    na_ontap_snapmirror:
      state: present
      update: true
      source_volume: "{{ src_vol_name }}"
      destination_volume: "{{ dst_vol_name }}"
      source_vserver: "{{ src_vserver }}"
      destination_vserver: "{{ dst_vserver }}"
      schedule: "{{ schedule }}"
      policy: "{{ policy }}"
      max_transfer_rate: "{{ max_transfer_rate }}"
      hostname: "{{ dst_hostname }}"
      username: "{{ dst_username }}"
      password: "{{ dst_password }}"
      https: true
      validate_certs: false
  - debug:
      msg: "The Mirror Relationship has been updated."
