---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Destination Volume creation
  tasks:
  - name: Destination Volume Creation
    na_ontap_volume:
      state: present
      name: "{{ dst_vol_name }}"
      vserver: "{{ dst_vserver }}"
      aggregate_name: "{{ dst_aggr }}"
      size: "{{ dst_vol_size }}"
      size_unit: gb
      policy: default
      type: DP
      hostname: "{{ dst_hostname }}"
      username: "{{ dst_username }}"
      password: "{{ dst_password }}"
      https: true
      validate_certs: false
#    ignore_errors: yes
#    when: "'No element by given name style' in command_result.stderr"
  - debug:
      msg: "The Destination Volume has been created"
